% Extract values from fisheyeIntrinsics
load('calibrationSession.mat')

cameraParams = calibrationSession.CameraParameters;
K_fisheye = cameraParams.Intrinsics;
mappingCoeffs = K_fisheye.MappingCoefficients; % [fx, k2, k3, k4]
imageSize = K_fisheye.ImageSize;               % [height, width]
center = K_fisheye.DistortionCenter;           % [cx, cy]

% Focal length is the first mapping coefficient
fx = mappingCoeffs(1);
fy = fx;  % Typically assumed equal for square pixels
cx = center(1);
cy = center(2);

% Generate YAML content
yaml = sprintf([ ...
'image_width: %d\n' ...
'image_height: %d\n' ...
'camera_name: fisheye_cam\n' ...
'distortion_model: fisheye\n' ...
'camera_matrix:\n' ...
'  rows: 3\n' ...
'  cols: 3\n' ...
'  data: [%.10f, 0.0, %.10f, 0.0, %.10f, %.10f, 0.0, 0.0, 1.0]\n' ...
'distortion_coefficients:\n' ...
'  rows: 1\n' ...
'  cols: 4\n' ...
'  data: [%.10f, %.10e, %.10e, %.10e]\n' ...
'rectification_matrix:\n' ...
'  rows: 3\n' ...
'  cols: 3\n' ...
'  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]\n' ...
'projection_matrix:\n' ...
'  rows: 3\n' ...
'  cols: 4\n' ...
'  data: [%.10f, 0.0, %.10f, 0.0, 0.0, %.10f, %.10f, 0.0, 0.0, 0.0, 1.0, 0.0]\n'], ...
imageSize(2), imageSize(1), ...
fx, cx, fy, cy, ...
mappingCoeffs(2), mappingCoeffs(3), mappingCoeffs(4), 0.0, ...
fx, cx, fy, cy);

% Print or save YAML
disp(yaml);

% Optional: Save to file
yamlFilePath = fullfile(save_path, 'fisheye_camera.yaml');
fid = fopen(yamlFilePath, 'w');
fprintf(fid, '%s', yaml);
fclose(fid);

disp(['YAML file saved to: ' yamlFilePath]);
